package org.jasr.facundia.verbs;

public enum Verb {
    INF,PRES_IND_YO,
    GER, PRES_IMP_USTED, CO_SUB_EL, CO_SUB_YO, FUT_SUB_NOSOTROS, PRES_IMP_VOS, PRES_SUB_YO, PART, CO_SUB_VOS, CO_SUB_ELLOS, PRES_IMP_TU, CO_SUB_NOSOTROS, PRES_IND_TU, PRES_IMP_VOSEO, CO_SUB_TU, FUT_SUB_ELLOS, FUT_SUB_YO, FUT_SUB_VOS, PRES_SUB_TU, PRES_SUB_NOSOTROS, PRES_SUB_USTEDES, PRES_SUB_ELLOS, PRET_IND_YO, FUT_SUB_TU, PRES_IMP_USTEDES, PRES_SUB_VOS,  PRES_IND_VOSEO, COP_IND_YO, COP_IND_EL, COP_IND_TU, PRES_IND_ELLOS, PRES_IND_USTEDES, PRES_IND_EL, PRES_IND_NOSOTROS, PRES_IND_VOS, PRET_IND_TU, PRET_IND_VOSEO, PRET_IND_VOS, PRET_IND_NOSOTROS, PRET_IND_EL, PRET_IND_ELLOS, PRET_IND_USTEDES, FUT_IND_YO, FUT_IND_TU, FUT_IND_VOS, POS_IND_YO, POS_IND_TU, POS_IND_VOSEO, POS_IND_VOS, POS_IND_EL, POS_IND_NOSOTROS, POS_IND_USTEDES, POS_IND_ELLOS, FUT_IND_EL, FUT_IND_NOSOTROS, FUT_IND_ELLOS, COP_IND_NOSOTROS, COP_IND_VOS, COP_IND_ELLOS
    
}
